language: java
sudo: false # faster builds
jdk:
- oraclejdk8
script: "mvn cobertura:cobertura"
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  skip_cleanup: true
  on: master
after_success:
- bash <(curl -s https://codecov.io/bash)