DROP TABLE IF EXISTS REQUEST;

CREATE TABLE REQUEST
(
  ACCOUNT_CODE VARCHAR,
  TARGET_DEVICE VARCHAR,
  PLUGIN_VERSION VARCHAR,
  PING_TIME INTEGER,
  HOSTS VARCHAR,
  PRIMARY KEY (ACCOUNT_CODE, TARGET_DEVICE, PLUGIN_VERSION)
);

CREATE INDEX account_code ON REQUEST(ACCOUNT_CODE);
